enum Complexity { simple, challenging, hard }

enum Affordability { affordable, pricey, luxurious }

class Trip {
  final String id;
  final List<String> categories;
  final String title;
  final String imageUrl;
  final List<String> activities;
  final List<String> program;
  final int duration;
  final Complexity complexity;
  final Affordability affordability;
  final bool isGlutenFree;
  final bool isLactoseFree;
  final bool isVegan;
  final bool isVegetarian;
  final double price;

  const Trip({
    required this.id,
    required this.categories,
    required this.title,
    required this.imageUrl,
    required this.activities,
    required this.program,
    required this.duration,
    required this.complexity,
    required this.affordability,
    required this.isGlutenFree,
    required this.isLactoseFree,
    required this.isVegan,
    required this.isVegetarian,
    required this.price,
  });
}

const dummyTrips = [
  Trip(
    id: 't1',
    categories: ['c1', 'c2'],
    title: 'Mountains',
    price: 199.99,
    imageUrl: 'assets/images/1.jpg',
    activities: ['Hiking', 'Sightseeing', 'Photography', 'Camping'],
    program: [
      'Day 1: Arrival and setup',
      'Day 2: Hiking to the summit',
      'Day 3: Sightseeing and photography',
      'Day 4: Departure',
    ],
    duration: 4,
    complexity: Complexity.challenging,
    affordability: Affordability.affordable,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Trip(
    id: 't2',
    categories: ['c2'],
    title: 'Hawaii',
    price: 1299.99,
    imageUrl: 'assets/images/2.webp',
    activities: ['Surfing', 'Swimming', 'Sunbathing'],
    program: [
      'Day 1: Arrival at the resort',
      'Day 2: Surfing lessons',
      'Day 3: Beach relaxation',
      'Day 4: Island tour',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.simple,
    affordability: Affordability.luxurious,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Trip(
    id: 't3',
    categories: ['c3'],
    title: 'Grand Canyon',
    price: 499.99,
    imageUrl: 'assets/images/3.jpg',
    activities: ['Hiking', 'Photography', 'Helicopter tour'],
    program: [
      'Day 1: Arrival and check-in',
      'Day 2: Hiking the trails',
      'Day 3: Helicopter tour',
      'Day 4: Departure',
    ],
    duration: 4,
    complexity: Complexity.challenging,
    affordability: Affordability.pricey,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Trip(
    id: 't4',
    categories: ['c4'],
    title: 'New York City',
    price: 899.99,
    imageUrl: 'assets/images/4.jpg',
    activities: ['Sightseeing', 'Shopping', 'Broadway show', 'Museums'],
    program: [
      'Day 1: Arrival and Times Square',
      'Day 2: Statue of Liberty',
      'Day 3: Shopping on 5th Avenue',
      'Day 4: Broadway show',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.simple,
    affordability: Affordability.luxurious,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Trip(
    id: 't5',
    categories: ['c1', 'c5'],
    title: 'Skiing in the Alps',
    price: 1500.00,
    imageUrl: 'assets/images/5.jpg',
    activities: ['Skiing', 'Snowboarding', 'Apres-ski'],
    program: [
      'Day 1: Arrival and equipment rental',
      'Day 2: Skiing lessons',
      'Day 3: Full day skiing',
      'Day 4: Snowboarding',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.hard,
    affordability: Affordability.luxurious,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: true,
  ),
  Trip(
    id: 't6',
    categories: ['c6'],
    title: 'Safari in Kenya',
    price: 2500.00,
    imageUrl: 'assets/images/6.webp',
    activities: ['Game drives', 'Photography', 'Cultural visits'],
    program: [
      'Day 1: Arrival in Nairobi',
      'Day 2: Transfer to Masai Mara',
      'Day 3: Full day game drive',
      'Day 4: Cultural village visit',
      'Day 5: Morning game drive and departure',
    ],
    duration: 5,
    complexity: Complexity.simple,
    affordability: Affordability.luxurious,
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Trip(
    id: 't7',
    categories: ['c7'],
    title: 'Kyoto Temples',
    price: 1100.00,
    imageUrl: 'assets/images/7.webp',
    activities: ['Temple visits', 'Tea ceremony', 'Gardens'],
    program: [
      'Day 1: Arrival in Kyoto',
      'Day 2: Kinkaku-ji and Ryoan-ji',
      'Day 3: Fushimi Inari Taisha',
      'Day 4: Arashiyama Bamboo Grove',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.simple,
    affordability: Affordability.pricey,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: true,
  ),
  Trip(
    id: 't8',
    categories: ['c8'],
    title: 'Paris Getaway',
    price: 1300.00,
    imageUrl: 'assets/images/8.jpg',
    activities: ['Eiffel Tower', 'Louvre Museum', 'Seine Cruise'],
    program: [
      'Day 1: Arrival and Eiffel Tower',
      'Day 2: Louvre Museum',
      'Day 3: Montmartre and Sacré-Cœur',
      'Day 4: Seine River Cruise',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.simple,
    affordability: Affordability.luxurious,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: true,
  ),
  Trip(
    id: 't9',
    categories: ['c9'],
    title: 'Rome History',
    price: 1000.00,
    imageUrl: 'assets/images/9.webp',
    activities: ['Colosseum', 'Vatican City', 'Trevi Fountain'],
    program: [
      'Day 1: Arrival and Trevi Fountain',
      'Day 2: Colosseum and Roman Forum',
      'Day 3: Vatican Museums and Sistine Chapel',
      'Day 4: Pantheon and Piazza Navona',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.simple,
    affordability: Affordability.pricey,
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: true,
  ),
  Trip(
    id: 't10',
    categories: ['c10'],
    title: 'Iceland Road Trip',
    price: 1800.00,
    imageUrl: 'assets/images/10.webp',
    activities: ['Waterfall chasing', 'Glacier hiking', 'Hot springs'],
    program: [
      'Day 1: Arrival and Blue Lagoon',
      'Day 2: Golden Circle',
      'Day 3: South Coast waterfalls',
      'Day 4: Jökulsárlón Glacier Lagoon',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.challenging,
    affordability: Affordability.luxurious,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: true,
  ),
  Trip(
    id: 't11',
    categories: ['c1'],
    title: 'Amazon Rainforest',
    price: 1600.00,
    imageUrl: 'assets/images/11.webp',
    activities: ['Jungle trekking', 'Canoeing', 'Wildlife spotting'],
    program: [
      'Day 1: Arrival at lodge',
      'Day 2: Jungle trek',
      'Day 3: Canoe trip',
      'Day 4: Night safari',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.hard,
    affordability: Affordability.pricey,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Trip(
    id: 't12',
    categories: ['c2'],
    title: 'Maldives Relax',
    price: 3000.00,
    imageUrl: 'assets/images/12.webp',
    activities: ['Snorkeling', 'Spa treatments', 'Dining under stars'],
    program: [
      'Day 1: Arrival by seaplane',
      'Day 2: Beach relaxation',
      'Day 3: Snorkeling trip',
      'Day 4: Sunset cruise',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.simple,
    affordability: Affordability.luxurious,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: true,
  ),
  Trip(
    id: 't13',
    categories: ['c3'],
    title: 'Machu Picchu',
    price: 1400.00,
    imageUrl: 'assets/images/13.webp',
    activities: ['Hiking Inca Trail', 'History tour', 'Llama spotting'],
    program: [
      'Day 1: Arrival in Cusco',
      'Day 2: Acclimatization',
      'Day 3: Start Inca Trail',
      'Day 4: Arrive at Machu Picchu',
      'Day 5: Return to Cusco',
    ],
    duration: 5,
    complexity: Complexity.hard,
    affordability: Affordability.pricey,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: true,
  ),
  Trip(
    id: 't14',
    categories: ['c4'],
    title: 'London Calling',
    price: 1200.00,
    imageUrl: 'assets/images/1.jpg',
    activities: ['Big Ben', 'British Museum', 'London Eye'],
    program: [
      'Day 1: Arrival and Big Ben',
      'Day 2: British Museum',
      'Day 3: Tower of London',
      'Day 4: Buckingham Palace',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.simple,
    affordability: Affordability.pricey,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: true,
  ),
  Trip(
    id: 't15',
    categories: ['c5'],
    title: 'Swiss Lakes',
    price: 1700.00,
    imageUrl: 'assets/images/2.webp',
    activities: ['Boat tours', 'Hiking', 'Chocolate tasting'],
    program: [
      'Day 1: Arrival in Geneva',
      'Day 2: Lake Geneva boat tour',
      'Day 3: Trip to Montreux',
      'Day 4: Hiking in the hills',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.simple,
    affordability: Affordability.luxurious,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: true,
  ),
  Trip(
    id: 't16',
    categories: ['c6'],
    title: 'Great Barrier Reef',
    price: 2200.00,
    imageUrl: 'assets/images/3.jpg',
    activities: ['Scuba diving', 'Snorkeling', 'Island hopping'],
    program: [
      'Day 1: Arrival in Cairns',
      'Day 2: Boat trip to outer reef',
      'Day 3: Scuba diving',
      'Day 4: Green Island visit',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.challenging,
    affordability: Affordability.luxurious,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Trip(
    id: 't17',
    categories: ['c7'],
    title: 'Taj Mahal Visit',
    price: 900.00,
    imageUrl: 'assets/images/4.jpg',
    activities: ['Taj Mahal', 'Agra Fort', 'Local markets'],
    program: [
      'Day 1: Arrival in Delhi',
      'Day 2: Travel to Agra',
      'Day 3: Sunrise at Taj Mahal',
      'Day 4: Agra Fort visit',
      'Day 5: Return to Delhi and departure',
    ],
    duration: 5,
    complexity: Complexity.simple,
    affordability: Affordability.affordable,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: true,
  ),
  Trip(
    id: 't18',
    categories: ['c8'],
    title: 'Santorini Sunset',
    price: 1600.00,
    imageUrl: 'assets/images/5.jpg',
    activities: ['Sunset watching', 'Wine tasting', 'Boat tour'],
    program: [
      'Day 1: Arrival in Thira',
      'Day 2: Explore Oia',
      'Day 3: Volcano boat tour',
      'Day 4: Wine tasting tour',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.simple,
    affordability: Affordability.pricey,
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: true,
  ),
  Trip(
    id: 't19',
    categories: ['c9'],
    title: 'Dubai Luxury',
    price: 2800.00,
    imageUrl: 'assets/images/6.webp',
    activities: ['Burj Khalifa', 'Desert Safari', 'Shopping'],
    program: [
      'Day 1: Arrival and Dubai Mall',
      'Day 2: Burj Khalifa top view',
      'Day 3: Desert Safari with dinner',
      'Day 4: Palm Jumeirah',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.simple,
    affordability: Affordability.luxurious,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: true,
  ),
  Trip(
    id: 't20',
    categories: ['c10'],
    title: 'New Zealand Adventure',
    price: 2100.00,
    imageUrl: 'assets/images/7.webp',
    activities: ['Bungee jumping', 'Hiking', 'Milford Sound cruise'],
    program: [
      'Day 1: Arrival in Queenstown',
      'Day 2: Bungee jumping',
      'Day 3: Trip to Milford Sound',
      'Day 4: Hiking Ben Lomond',
      'Day 5: Departure',
    ],
    duration: 5,
    complexity: Complexity.challenging,
    affordability: Affordability.pricey,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
];
